"""add customer table

Revision ID: 96b562dcfaab
Revises: c7a6584aca4d
Create Date: 2025-08-27 17:28:50.308392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b562dcfaab'
down_revision: Union[str, Sequence[str], None] = 'c7a6584aca4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'menu_items', ['id'])
    op.create_unique_constraint(None, 'restaurants', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurants', type_='unique')
    op.drop_constraint(None, 'menu_items', type_='unique')
    op.drop_table('customer')
    # ### end Alembic commands ###
