"""Added Inventory table

Revision ID: 99035e5a8b7c
Revises: 96b562dcfaab
Create Date: 2025-09-10 18:46:30.464279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99035e5a8b7c'
down_revision: Union[str, Sequence[str], None] = '96b562dcfaab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_status_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=False),
    sa.Column('column_mappings', sa.JSON(), nullable=False),
    sa.Column('result_status', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'customer', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='unique')
    op.drop_table('inventory_status_mappings')
    # ### end Alembic commands ###
